export const headerRef = document.querySelector('.js-page-header');
export const logoRef = document.querySelector('.js-logo');
export const navListRef = document.querySelector('.js-navigation-list');
export const homeButtonRef = document.querySelector('[data-button="home"]');
export const libraryButtonRef = document.querySelector('[data-button="library"]');
export const authBtnRef = document.querySelector('[data-button="auth"]');
export const headerDynamicContainerRef = document.querySelector('header .js-dynamic-container');
export const themeSwitcherRef = document.querySelector('#theme-switch-toggle');
export const listFilmsRef = document.querySelector('section .movie__list');
export const modal = document.querySelector('.modal');
export const teamBtn = document.querySelector('.button-team');
export const backdrop = document.querySelector('.backdrop');
export const searchErrRef = document.querySelector('.search-error');
export const watchedFilmList = document.querySelector('.watched-films');
export const paginationRef = document.querySelector('.pagination');
